# Generated by Django 4.0.6 on 2022-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_timeslot_id_alter_timeslot_slotend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slotStart',
            field=models.DateTimeField(null=True),
        ),
    ]
